(test) Add missing blocks reg test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -27,7 +27,15 @@ idxr() {
 }
 
 dl_mainnet() {
-    "$BLOCKS_FETCHER" mina_network_block_data "$1" mainnet "$2"
+    "$BLOCKS_FETCHER" mina_network_block_data 2 "$1" mainnet "$2"
+}
+
+dl_mainnet_single() {
+    "$BLOCKS_FETCHER" mina_network_block_data "$1" "$1" mainnet "$2"
+}
+
+dl_mainnet_range() {
+    "$BLOCKS_FETCHER" mina_network_block_data "$1" "$2" mainnet "$3"
 }
 
 assert() {
@@ -39,6 +47,17 @@ assert() {
         exit 1
     else
         echo "Test Passed!"
+    fi
+}
+
+assert_directory_exists() {
+    directory="$1"
+
+    if [ ! -d "$directory" ]; then
+        echo "Test Failed: Expected directory $directory to exist, but it does not."
+        exit 1
+    else
+        echo "Test Passed: Directory $directory exists."
     fi
 }
 
@@ -100,21 +119,6 @@ test_indexer_cli_reports() {
         grep -iq "Usage: mina-indexer transactions"
 }
 
-# Indexer server config passes cli with minimal args
-test_indexer_basic_start() {
-    test=test_indexer_basic_start
-
-    setup
-    idxr server cli \
-        --startup-dir ./blocks \
-        --watch-dir ./blocks \
-        --database-dir ./database \
-        --log-dir ./logs &
-    sleep 1
-    idxr_pid=$(pgrep -c mina-indexer)
-    teardown
-}
-
 # Indexer server starts up without any precomputed blocks
 test_server_startup() {
     test=test_server_startup
@@ -125,10 +129,11 @@ test_server_startup() {
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 10
+    sleep 5
 
     result=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
     assert '3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ' $result
+
     idxr_pid=$(pgrep -c mina-indexer)
     teardown
 }
@@ -154,62 +159,17 @@ test_ipc_is_available_immediately() {
     teardown
 }
 
-# Indexer server reports correct balance for Genesis Ledger Account
-test_account_balance_cli() {
-    test=test_account_balance_cli
-
-    setup
-    idxr server cli \
-        --startup-dir ./blocks \
-        --watch-dir ./blocks \
-        --database-dir ./database \
-        --log-dir ./logs &
-    sleep 10
-
-    result=$(idxr account -j --public-key B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk | jq -r .balance)
-    assert '148837200000000' $result
-    idxr_pid=$(pgrep -c mina-indexer)
-    teardown
-}
-
-# Indexer server returns the correct account
-test_account_public_key_json() {
-    test=test_account_public_key_json
-    setup
-
-    idxr server cli \
-        --startup-dir ./blocks \
-        --watch-dir ./blocks \
-        --database-dir ./database \
-        --log-dir ./logs &
-    sleep 5
-    result=$(idxr account -j --public-key B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk | jq -r .public_key)
-    assert 'B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk' $result
-    idxr_pid=$(pgrep -c mina-indexer)
-    teardown
-}
-
-assert_directory_exists() {
-    directory="$1"
-
-    if [ ! -d "$directory" ]; then
-        echo "Test Failed: Expected directory $directory to exist, but it does not."
-        exit 1
-    else
-        echo "Test Passed: Directory $directory exists."
-    fi
-}
-
+# Indexer server starts and creates directories with minimal args
 test_startup_dirs_get_created() {
     test=test_startup_dirs_get_created
-    setup
 
+    setup
     idxr server cli \
         --startup-dir ./startup-blocks \
         --watch-dir ./watch-blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 5
+    sleep 1
 
     assert_directory_exists "./startup-blocks"
     assert_directory_exists "./watch-blocks"
@@ -220,18 +180,57 @@ test_startup_dirs_get_created() {
     teardown
 }
 
-# Indexer server returns the correct canonical tip
-test_canonical_tip() {
-    test=test_canonical_tip
-    setup
+# Indexer server reports correct balance for Genesis Ledger Account
+test_account_balance_cli() {
+    test=test_account_balance_cli
 
-    dl_mainnet 15 ./blocks
+    setup
     idxr server cli \
         --startup-dir ./blocks \
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 20
+    sleep 5
+
+    result=$(idxr account -j --public-key B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk | jq -r .balance)
+    assert '148837200000000' $result
+
+    idxr_pid=$(pgrep -c mina-indexer)
+    teardown
+}
+
+# Indexer server returns the correct account
+test_account_public_key_json() {
+    test=test_account_public_key_json
+
+    setup
+    idxr server cli \
+        --startup-dir ./blocks \
+        --watch-dir ./blocks \
+        --database-dir ./database \
+        --log-dir ./logs &
+    sleep 5
+
+    result=$(idxr account -j --public-key B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk | jq -r .public_key)
+    assert 'B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk' $result
+
+    idxr_pid=$(pgrep -c mina-indexer)
+    teardown
+}
+
+# Indexer server returns the correct canonical tip
+test_canonical_tip() {
+    test=test_canonical_tip
+
+    setup
+    dl_mainnet 15 ./blocks
+
+    idxr server cli \
+        --startup-dir ./blocks \
+        --watch-dir ./blocks \
+        --database-dir ./database \
+        --log-dir ./logs &
+    sleep 5
     
     state_hash=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
     blockchain_length=$(idxr summary -j | jq -r .witness_tree.canonical_tip_length)
@@ -243,19 +242,88 @@ test_canonical_tip() {
     teardown
 }
 
-# Indexer server returns the correct best chain
-test_best_chain() {
-    test=test_best_chain
-    setup
-    mkdir best_chain
+# Indexer handles missing blocks correctly
+test_missing_blocks() {
+    test=test_missing_blocks
 
-    dl_mainnet 12 ./blocks
-    RUST_BACKTRACE=1 idxr server cli \
+    setup
+    dl_mainnet 10 ./blocks
+    dl_mainnet_range 12 20 ./blocks # missing 11
+    dl_mainnet_range 22 30 ./blocks # missing 21
+
+    idxr server cli \
         --startup-dir ./blocks \
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 20
+    sleep 5
+
+    # start out missing block 11 & 21
+    num_dangling=$(idxr summary -j | jq -r .witness_tree.num_dangling)
+    best_hash=$(idxr summary -j | jq -r .witness_tree.best_tip_hash)
+    best_length=$(idxr summary -j | jq -r .witness_tree.best_tip_length)
+    canonical_hash=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
+    canonical_length=$(idxr summary -j | jq -r .witness_tree.canonical_tip_length)
+
+    assert 2 $num_dangling
+    assert 10 $best_length
+    assert 1 $canonical_length
+    assert '3NKGgTk7en3347KH81yDra876GPAUSoSePrfVKPmwR1KHfMpvJC5' $best_hash
+    assert '3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ' $canonical_hash
+
+    # add missing block which connects the dangling branches
+    dl_mainnet_single 21 ./blocks
+    sleep 1
+
+    # dangling branches combine
+    # no new canonical blocks
+    num_dangling=$(idxr summary -j | jq -r .witness_tree.num_dangling)
+    best_hash=$(idxr summary -j | jq -r .witness_tree.best_tip_hash)
+    best_length=$(idxr summary -j | jq -r .witness_tree.best_tip_length)
+    canonical_hash=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
+    canonical_length=$(idxr summary -j | jq -r .witness_tree.canonical_tip_length)
+
+    assert 1 $num_dangling
+    assert 10 $best_length
+    assert 1 $canonical_length
+    assert '3NKGgTk7en3347KH81yDra876GPAUSoSePrfVKPmwR1KHfMpvJC5' $best_hash
+    assert '3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ' $canonical_hash
+
+    # add remaining missing block
+    dl_mainnet_single 11 ./blocks
+    sleep 1
+
+    # dangling branches move into the root branch
+    num_dangling=$(idxr summary -j | jq -r .witness_tree.num_dangling)
+    best_hash=$(idxr summary -j | jq -r .witness_tree.best_tip_hash)
+    best_length=$(idxr summary -j | jq -r .witness_tree.best_tip_length)
+    canonical_hash=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
+    canonical_length=$(idxr summary -j | jq -r .witness_tree.canonical_tip_length)
+
+    assert 0 $num_dangling
+    assert 30 $best_length
+    assert 20 $canonical_length
+    assert '3NLsuVoPLnRzdzjrdFKWmkqNzqNEQxrfa7iQMwu1WxcstZjmorUs' $best_hash
+    assert '3NLPpt5SyVnD1U5uJAqR3DL1Cqj5dG26SuWutRQ6AQpbQtQUWSYA' $canonical_hash
+
+    idxr_pid=$(pgrep -c mina-indexer)
+    teardown
+}
+
+# Indexer server returns the correct best chain
+test_best_chain() {
+    test=test_best_chain
+
+    setup
+    mkdir best_chain
+    dl_mainnet 12 ./blocks
+
+    idxr server cli \
+        --startup-dir ./blocks \
+        --watch-dir ./blocks \
+        --database-dir ./database \
+        --log-dir ./logs &
+    sleep 5
 
     result=$(idxr best-chain -n 1 | jq -r .[0].state_hash)
     assert '3NKkJDmNZGYdKVDDJkkamGdvNzASia2SXxKpu18imps7KqbNXENY' $result
@@ -299,16 +367,17 @@ test_best_chain() {
 # Indexer server returns correct ledgers
 test_ledgers() {
     test=test_ledgers
+
     setup
     mkdir ledgers
-
     dl_mainnet 15 ./blocks
+
     idxr server cli \
         --startup-dir ./blocks \
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 20
+    sleep 5
 
     pk='B62qp1RJRL7x249Z6sHCjKm1dbkpUWHRdiQbcDaz1nWUGa9rx48tYkR'
 
@@ -345,15 +414,16 @@ test_ledgers() {
 # Indexer server syncs with existing rocksdb
 test_sync() {
     test=test_sync
-    setup
 
+    setup
     dl_mainnet 15 ./blocks
+
     idxr server cli \
         --startup-dir ./blocks \
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 20
+    sleep 5
 
     # pre-sync results
     canonical_hash=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
@@ -372,7 +442,7 @@ test_sync() {
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 20
+    sleep 5
 
     # post-sync reults
     canonical_hash_sync=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
@@ -392,15 +462,16 @@ test_sync() {
 # Indexer server replays events
 test_replay() {
     test=test_replay
-    setup
 
+    setup
     dl_mainnet 15 ./blocks
+
     idxr server cli \
         --startup-dir ./blocks \
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 20
+    sleep 5
 
     # pre-replay results
     canonical_hash=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
@@ -420,7 +491,7 @@ test_replay() {
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 20
+    sleep 5
 
     # post-replay reults
     canonical_hash_replay=$(idxr summary -j | jq -r .witness_tree.canonical_tip_hash)
@@ -435,7 +506,7 @@ test_replay() {
     assert '15' $best_length
     assert $best_length $best_length_replay
     assert '15' $num_blocks
-    assert '15' $num_blocks_replay
+    assert $num_blocks $num_blocks_replay
 
     idxr_pid=$(pgrep -c mina-indexer)
     teardown
@@ -444,16 +515,17 @@ test_replay() {
 # Indexer server returns correct transactions
 test_transactions() {
     test=test_transactions
+
     setup
     mkdir transactions
-
     dl_mainnet 13 ./blocks
+
     idxr server cli \
         --startup-dir ./blocks \
         --watch-dir ./blocks \
         --database-dir ./database \
         --log-dir ./logs &
-    sleep 15
+    sleep 5
 
     # basic transaction queries
     transactions=$(idxr transactions --public-key B62qp1RJRL7x249Z6sHCjKm1dbkpUWHRdiQbcDaz1nWUGa9rx48tYkR -j | jq -r .)
@@ -548,13 +620,13 @@ test_checkpoint() {
 if [ "$#" -eq 0 ]; then
     # No arguments provided, run all tests
     test_indexer_cli_reports
-    test_indexer_basic_start
     test_server_startup
     test_ipc_is_available_immediately
+    test_startup_dirs_get_created
     test_account_balance_cli
     test_account_public_key_json
-    test_startup_dirs_get_created
     test_canonical_tip
+    test_missing_blocks
     test_best_chain
     test_ledgers
     test_sync
@@ -566,13 +638,13 @@ else
     for test_name in "$@"; do
         case $test_name in
             "test_indexer_cli_reports") test_indexer_cli_reports ;;
-            "test_indexer_basic_start") test_indexer_basic_start ;;
             "test_server_startup") test_server_startup ;;
             "test_ipc_is_available_immediately") test_ipc_is_available_immediately ;;
+            "test_startup_dirs_get_created") test_startup_dirs_get_created ;;
             "test_account_balance_cli") test_account_balance_cli ;;
             "test_account_public_key_json") test_account_public_key_json ;;
-            "test_startup_dirs_get_created") test_startup_dirs_get_created ;;
             "test_canonical_tip") test_canonical_tip ;;
+            "test_missing_blocks") test_missing_blocks ;;
             "test_best_chain") test_best_chain ;;
             "test_ledgers") test_ledgers ;;
             "test_sync") test_sync ;;
