Check for existence, not directory

diff --git a/ops/productionize b/ops/productionize
--- a/ops/productionize
+++ b/ops/productionize
@@ -4,11 +4,11 @@ set -eu
 
 MAGNITUDE=4
 
-if [ -d /mnt/mina-indexer-prod ]; then
+if [ -e /mnt/mina-indexer-prod ]; then
   echo "Productionizing with 10^${MAGNITUDE} blocks."
   ./ops/deploy /mnt/mina-indexer-prod/magnitude-"$MAGNITUDE" "$MAGNITUDE"
 else
   >&2 echo '/mnt/mina-indexer-prod must exist to perform regression tests.'
-  >@2 echo 'Failure.'
+  >&2 echo 'Failure.'
   exit 1
 fi
diff --git a/ops/regression-test b/ops/regression-test
--- a/ops/regression-test
+++ b/ops/regression-test
@@ -2,11 +2,11 @@
 
 set -eu
 
-if [ -d /mnt/mina-indexer-dev ]; then
+if [ -e /mnt/mina-indexer-dev ]; then
   echo "Regression testing..."
   ./tests/regression "$@"
 else
   >&2 echo '/mnt/mina-indexer-dev must exist to perform regression tests.'
-  >@2 echo 'Failure.'
+  >&2 echo 'Failure.'
   exit 1
 fi
diff --git a/ops/tier3-test b/ops/tier3-test
--- a/ops/tier3-test
+++ b/ops/tier3-test
@@ -4,11 +4,11 @@ set -eu
 
 MAGNITUDE=4
 
-if [ -d /mnt/mina-indexer-test ]; then
+if [ -e /mnt/mina-indexer-test ]; then
   echo "Testing (tier 3) with 10^${MAGNITUDE} blocks."
   ./ops/deploy /mnt/mina-indexer-test/magnitude-"$MAGNITUDE" "$MAGNITUDE" test
 else
-  >&2 echo '/mnt/mina-indexer-dev must exist to perform regression tests.'
-  >@2 echo 'Failure.'
+  >&2 echo '/mnt/mina-indexer-test must exist to perform regression tests.'
+  >&2 echo 'Failure.'
   exit 1
 fi
